#!/bin/bash

#
# CLONE GITHUB PROJECTS (CLASSIC) CARDS
#
# Dmytri Kleiner <dk@trick.ca>
#
# derived from https://blog.termian.dev/posts/project-cards-copy-github/
#

#
# FUNCTIONS
#

RED='\033[0;31m'
YELLOW='\033[1;33m'
NOCOLOR='\033[0m'

usage () {
  echo
  echo "clone [options]"
  echo
  echo "Options:"
  echo "  -d|--debug     show debug output"
  echo "  -q|--quiet     suppress output"
  echo "  -r|--repo      set target repo and clone"
  echo "  -s|--setup     do setup steps only and exit"
  echo "  -c|--cleanup   clean up dependencies and exit"
  echo "  -h|--help      show this help and exit"
}

log () {
  local M
  if [ -z "$quiet" ]; then
    if [ -n "$1" ]
    then
        M="$*"
    else
        read M 
    fi

    >&1 echo "$M"
  fi
}

debug () {
  if [ -n "$debug" ]; then
    if [ -n "$1" ]
    then
        M="$*"
    else
        read M 
    fi

    >&1 echo -e "${YELLOW}Debug:${NOCOLOR} $M"
  fi
}

error () {
  if [ -n "$1" ]
  then
      M="$*"
  else
      read M 
  fi

  >&2 echo -e "${RED}Error:${NOCOLOR} $M"
  exit 1
}

clean () {
  local packages
  mapfile -t packages < <($BASHERPM list)

  log packages to uninstall: ${#packages[@]}
  for p in "${packages[@]}"; do
    $BASHERPM uninstall $p
    debug uninstall $p
  done
}

#
# SETUP
#


BASHER_ROOT="$PWD/basher"
BASHER_PREFIX="$BASHER_ROOT/cellar"
BASHER_PACKAGES_PATH="$BASHER_PREFIX/packages"
BASHERPM="$PWD/basher/bin/basher"

if ! type $BASHERPM &>/dev/null; then
  git clone --depth=1 https://github.com/basherpm/basher.git $BASHER_ROOT
fi

eval "$($BASHERPM init - bash)"

$BASHERPM install dmytri/simple_opts.sh &>/dev/null
source $BASHER_PACKAGES_PATH/dmytri/simple_opts.sh/lib/simple_opts.sh

opt --repo= -r
opt --clean -c
opt --setup -s
opt --quiet -q
opt --debug -d
opt --help -h
opt_parse $@

$BASHERPM install dmytri/jp 2>&1 | debug

if [ -n "$help" ]; then
  usage
  exit 0
fi

if [ -n "$clean" ]; then
  clean
  exit 0
fi

declare GH
hash gh 2>/dev/null && GH=gh || GH="${HOME}/gh/bin/gh"
if ! type $GH &>/dev/null; then
  error "gh should be in PATH or at ~/gh/bin/gh | https://github.com/cli/cli"
fi

GITHUB_TOKEN=$($GH auth token)
if [ -z "$GITHUB_TOKEN" ]; then
  $GH auth login -w -p https
  GITHUB_TOKEN=$($GH auth token)
fi
debug "Github Token: $GITHUB_TOKEN"

if [ -n "$setup" ]; then
  exit 0
fi

if [ -z "$repo" ]; then
  error "--repo is required"
  usage
  exit 1
fi

#
# CLONE
#

SOURCE_PROJECT_ID=14544235

TARGET_REPO=Garden-Delivery/"${repo}"
TARGET_PROJECT_ID=$($GH api \
  -H "Accept: application/vnd.github+json" \
  /repos/"${TARGET_REPO}"/projects 2>/dev/null \
  | jp .h '"id"' .keyval 2>/dev/null )

if [ -z "$TARGET_PROJECT_ID" ]; then
  error ${TARGET_REPO} must exist and have project columns copied into it
  exit 1
fi

mapfile -t targetColumnIds <  <($GH api \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/projects/${TARGET_PROJECT_ID}/columns \
  | jp [] .swap .map .cons \
  | jp .map .do '"id"' .keyval .done)

debug "Target project column ids: ${targetColumnIds[*]}"

mapfile -t sourceColumnIds < <($GH api \
  -H "Accept: application/vnd.github+json" \
  https://api.github.com/projects/${SOURCE_PROJECT_ID}/columns \
  | jp [] .swap .map .cons \
  | jp .map .do '"id"' .keyval .done)

debug "Source project column ids: ${sourceColumnIds[*]}"
  
if [ "${#sourceColumnIds[@]}" -ne "${#targetColumnIds[@]}" ]; then
    error "Different number of columns in between projects"
    exit 1
fi
    
log "cloning to $TARGET_REPO ..."
for sourceColumnIndex in "${!sourceColumnIds[@]}"
do
    sourceColumnId=${sourceColumnIds[$sourceColumnIndex]}
    sourceColumnId=${sourceColumnId//[^a-zA-Z0-9_]/}
    targetColumnId=${targetColumnIds[$sourceColumnIndex]}
    targetColumnId=${targetColumnId//[^a-zA-Z0-9_]/}
    $GH api \
      -H "Accept: application/vnd.github+json" \
      https://api.github.com/projects/columns/"${sourceColumnId}"/cards \
      2> error \
      | jp .map .do '"note"' .is_str .if .do .keyval .done .else .pop .done \
      | while read -r note; do
      data='{"note":'${note}'}'
      curl \
        -w 'HTTP Status: %{http_code}' --silent --output /dev/null \
        -X POST \
        -H "Authorization: token ${GITHUB_TOKEN}" \
        -H "Accept: application/vnd.github+json" \
        -d "${data}" \
        https://api.github.com/projects/columns/"${targetColumnId}"/cards \
        2>&1 | debug
    done
done
log "done"

#
# end
#
