#!/usr/bin/env bash

#
# install
#

if ! [[ "$PATH" =~ "/usr/bin:" ]]; then
  PATH="$PATH:/usb/bin"
fi

if ! [[ "$PATH" =~ "/usr/local/bin:" ]]; then
  PATH="$PATH:/usr/local/bin"
fi

BASHERPM="$PWD/basher/bin/basher"
eval "$($BASHERPM init - bash)"

$BASHERPM install svenfuchs/simple_opts.sh
$BASHERPM install spack/spack 1> /dev/null

. $BASHER_PACKAGES_PATH/spack/spack/share/spack/setup-env.sh

spack install -yn gh@2.18.1
spack load gh

gh auth login -w -p https

