#!/bin/bash

#
# SETUP
#

BASHERPM="$PWD/basher/bin/basher"
eval "$($BASHERPM init - zsh)"

$BASHERPM install dmytri/simple_opts.sh >/dev/null
source $BASHER_PACKAGES_PATH/dmytri/simple_opts.sh/lib/simple_opts.sh

declare GH
hash gh 2>/dev/null && GH=gh || GH="${HOME}/gh/bin/gh"
if ! type $GH 2>/dev/null 1>/dev/null; then
  echo "gh should be in PATH or at ~/gh/bin/gh | https://github.com/cli/cli"
  exit 1
  $BASHERPM install spack/spack >/dev/null

  source $BASHER_PACKAGES_PATH/spack/spack/share/spack/setup-env.sh
  spack install -yn gh@2.18.1
  spack load gh
fi

$GH auth token >/dev/null || $GH auth login -w -p https

